package Modelo;
// Generated 26-jun-2019 18:02:00 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Pedidoproducto generated by hbm2java
 */
@Entity
@Table(name="Pedidoproducto")
public class Pedidoproducto implements java.io.Serializable {
	@Id
	@Column(name="idproped")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer idproPed;
	
	@ManyToMany
	@JoinColumn(name="idpedidos")
	private int idpedidos;
	
	@ManyToMany
	@JoinColumn(name="idproductos")
	private String idproductos;
	
	@Column(name="cantidad")
	private Integer cantidad;

	public Pedidoproducto() {
	}

	public Pedidoproducto(int idpedidos) {
		this.idpedidos = idpedidos;
	}

	public Pedidoproducto(int idpedidos, String idproductos, Integer cantidad) {
		this.idpedidos = idpedidos;
		this.idproductos = idproductos;
		this.cantidad = cantidad;
	}

	public Integer getIdproPed() {
		return this.idproPed;
	}

	public void setIdproPed(Integer idproPed) {
		this.idproPed = idproPed;
	}

	public int getIdpedidos() {
		return this.idpedidos;
	}

	public void setIdpedidos(int idpedidos) {
		this.idpedidos = idpedidos;
	}

	public String getIdproductos() {
		return this.idproductos;
	}

	public void setIdproductos(String idproductos) {
		this.idproductos = idproductos;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
