package Modelo;
// Generated 26-jun-2019 18:02:00 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="Pedidos")
public class Pedidos implements java.io.Serializable {
	@Id
	@Column(name="idpedidos")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer idpedidos;
	
	@Column(name="fecha")
	private Date fecha;
	
	@Column(name="cantidad")
	private Float cantidad;
	
	@OneToMany
	@JoinColumn(name="idusuarios")
	private Integer idusuarios;

	public Pedidos() {
	}

	public Pedidos(Date fecha, Float cantidad, Integer idusuarios) {
		this.fecha = fecha;
		this.cantidad = cantidad;
		this.idusuarios = idusuarios;
	}

	public Integer getIdpedidos() {
		return this.idpedidos;
	}

	public void setIdpedidos(Integer idpedidos) {
		this.idpedidos = idpedidos;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	public Integer getIdusuarios() {
		return this.idusuarios;
	}

	public void setIdusuarios(Integer idusuarios) {
		this.idusuarios = idusuarios;
	}

}
