package Modelo;
// Generated 26-jun-2019 18:02:00 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="Productos")
public class Productos implements java.io.Serializable {
	@Id
	@Column(name="idproductos")
	private String idproductos;
	
	@Column(name="precio")
	private Float precio;
	
	@Column(name="descripcion")
	private String descripcion;

	public Productos() {
	}

	public Productos(String idproductos) {
		this.idproductos = idproductos;
	}

	public Productos(String idproductos, Float precio, String descripcion) {
		this.idproductos = idproductos;
		this.precio = precio;
		this.descripcion = descripcion;
	}

	public String getIdproductos() {
		return this.idproductos;
	}

	public void setIdproductos(String idproductos) {
		this.idproductos = idproductos;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
