package Modelo;
// Generated 26-jun-2019 18:02:00 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="Usuarios")
public class Usuarios implements java.io.Serializable {
	@Id
	@Column(name="idusuarios")
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer idusuarios;
	
	@Column(name="contraseña")
	private String contraseña;
	
	@Column(name="nombre")
	private String nombre;
	
	@Column(name="dni")
	private String dni;

	public Usuarios() {
	}

	public Usuarios(String contraseña, String nombre, String dni) {
		this.contraseña = contraseña;
		this.nombre = nombre;
		this.dni = dni;
	}

	public Integer getIdusuarios() {
		return this.idusuarios;
	}

	public void setIdusuarios(Integer idusuarios) {
		this.idusuarios = idusuarios;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

}
